#!/bin/bash

echo "==============================================================="
echo "Started pre-commit with bandit security analysis"
echo "==============================================================="

# Save the original timestamp of the Bandit report
original_timestamp=$(stat -c %Y bandit_report.csv)

# Run Bandit
bandit -r . -o bandit_report.csv -f csv

# Get the new timestamp
new_timestamp=$(stat -c %Y bandit_report.csv)



# Check if the Bandit report was generated
if [ "$original_timestamp" -ne "$new_timestamp" ]; then
  echo "*Updating Bandit report...*"
  git add bandit_report.csv
  echo "*Bandit report added to commit.*"
else
  echo "*No updates to Bandit report needed*."
fi

echo "==============================================================="
echo "Finished pre-commit"
echo "==============================================================="
